name: Auto approve

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: "Approve"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review --approve --body "Auto-approved by auto-approve.yml"
