name: "Auto-Merge"
on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: "Enable Auto-Merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          gh pr merge --repo $REPOSITORY $PR_NUMBER --auto --squash || true
          gh pr review $PR_NUMBER --body "Auto-approved by auto-approve.yml" --approve --repo $REPOSITORY
